### ISSUE TITLE
Problem with wifi loging

### ISSUE THREAD

**Issue by GSternik** [kd8bxp/Wifi_Display_Badge#2]
I used ESP32 devkit. After adding wifi credentials I flashed this code with success.
Unfortunately this device not loging into wifi. I do not know why. What I is wrong?

**Comment by kd8bxp** [comment]
no idea, you could try to reset your router, verify you have the right ssid, and password. make sure you have the latest board core for esp32. Maybe you can erase all the flash, and reset your device and try again. 
Did you get any kind of errors in the serial console?

**Comment by GSternik** [comment]
Thank You for the answere. This is a print in the serial console. Nothing more.
I checked SSID and password are right. Other code of the HTTP client works in this ESP32.
 
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6364
entry 0x400806b8

**Comment by kd8bxp** [comment]
You could try turning on debug verbose from the tools menu and re-upload the code. The above looks pretty normal to me looks like a normal power on/reset 
depending on what the verbose says you may do a google search and see if there is a answer.

-LeRoy
